"""
Phase 5 — Executive PDF Document Generator

Renders a VideoSummary object into a publication-grade PDF report with cover
banner, executive summary, key takeaways, table of contents, structured sections
with timestamps/quotes/actionable tips, key terminology glossary, deep-dive Q&A,
and running headers/footers with page numbers ("Page X of Y").
"""
from __future__ import annotations

import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    KeepTogether,
    ListFlowable,
    ListItem,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

from app.models import VideoSummary

TOC_MIN_SECTIONS = 3

PRIMARY_COLOR = colors.HexColor("#0F172A")    # Deep Slate / Navy
ACCENT_COLOR = colors.HexColor("#4338CA")     # Electric Indigo
ACCENT_LIGHT = colors.HexColor("#EEF2FF")     # Soft Indigo Fill
TEAL_COLOR = colors.HexColor("#0D9488")       # Cyan / Teal Accent
TEXT_DARK = colors.HexColor("#1E293B")        # Body text
TEXT_MUTED = colors.HexColor("#64748B")       # Secondary text
BORDER_COLOR = colors.HexColor("#E2E8F0")     # Light gray border


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw total page count
    and clean header/footer rules on every page."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_MUTED)

        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(0.85 * inch, 10.45 * inch, "YOUTUBE KNOWLEDGE DIGEST — EXECUTIVE REPORT")
            self.setStrokeColor(BORDER_COLOR)
            self.setLineWidth(0.5)
            self.line(0.85 * inch, 10.35 * inch, 7.65 * inch, 10.35 * inch)

        # Footer (all pages)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(7.65 * inch, 0.45 * inch, page_str)
        self.drawString(0.85 * inch, 0.45 * inch, "Generated by AI PDF Knowledge Engine")
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(0.85 * inch, 0.6 * inch, 7.65 * inch, 0.6 * inch)

        self.restoreState()


def _build_styles():
    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=PRIMARY_COLOR,
            alignment=TA_LEFT,
            spaceAfter=4,
        )
    )
    styles.add(
        ParagraphStyle(
            "DocTagline",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=11,
            leading=15,
            textColor=ACCENT_COLOR,
            spaceAfter=10,
        )
    )
    styles.add(
        ParagraphStyle(
            "MetaLine",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=TEXT_MUTED,
            spaceAfter=14,
        )
    )
    styles.add(
        ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=18,
            textColor=PRIMARY_COLOR,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        )
    )
    styles.add(
        ParagraphStyle(
            "SubSectionHeader",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=ACCENT_COLOR,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        )
    )
    styles.add(
        ParagraphStyle(
            "ExecutiveOverview",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14.5,
            textColor=TEXT_DARK,
            alignment=TA_JUSTIFY,
        )
    )
    styles.add(
        ParagraphStyle(
            "TakeawayItem",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14,
            textColor=TEXT_DARK,
            spaceAfter=4,
        )
    )
    styles.add(
        ParagraphStyle(
            "BulletText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=TEXT_DARK,
            spaceAfter=3,
        )
    )
    styles.add(
        ParagraphStyle(
            "DetailText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=TEXT_DARK,
            spaceBefore=3,
            spaceAfter=4,
        )
    )
    styles.add(
        ParagraphStyle(
            "QuoteText",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9.5,
            leading=14,
            textColor=PRIMARY_COLOR,
        )
    )
    styles.add(
        ParagraphStyle(
            "TipText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#065F46"),
        )
    )
    styles.add(
        ParagraphStyle(
            "TermName",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=13,
            textColor=ACCENT_COLOR,
        )
    )
    styles.add(
        ParagraphStyle(
            "TermDef",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=TEXT_DARK,
        )
    )
    styles.add(
        ParagraphStyle(
            "QAQuestion",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14,
            textColor=PRIMARY_COLOR,
            spaceBefore=6,
            spaceAfter=2,
            keepWithNext=True,
        )
    )
    styles.add(
        ParagraphStyle(
            "QAAnswer",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=TEXT_DARK,
            spaceAfter=6,
        )
    )
    styles.add(
        ParagraphStyle(
            "TOCHeading",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=PRIMARY_COLOR,
            spaceAfter=10,
        )
    )
    return styles


def _toc_entry_style(styles):
    return ParagraphStyle(
        "TOCEntry",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=TEXT_DARK,
    )


def _escape(text: str) -> str:
    if not text:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


CATEGORY_BADGES = {
    "lecture": "🎓 ACADEMIC LECTURE STUDY NOTES",
    "sports": "⚽ SPORTS MATCH RECAP & HIGHLIGHTS",
    "movie": "🎬 FILM REVIEW & PLOT DIGEST",
    "tutorial": "💻 TECHNICAL TUTORIAL & CODING GUIDE",
    "business": "📊 EXECUTIVE BUSINESS BRIEF",
    "podcast": "🎙️ PODCAST & INTERVIEW HIGHLIGHTS",
    "auto": "✦ AI VIDEO INTELLIGENCE DIGEST",
}


def generate_pdf(
    summary: VideoSummary,
    output_path: Path | str,
    source_url: str | None = None,
) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    styles = _build_styles()
    story = []

    include_toc = len(summary.sections) >= TOC_MIN_SECTIONS

    # --- Category Pill Badge ----------------------------------------------
    cat_key = (summary.category or "auto").lower()
    badge_label = CATEGORY_BADGES.get(cat_key, CATEGORY_BADGES["auto"])
    badge_style = ParagraphStyle(
        "CategoryBadge",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        textColor=ACCENT_COLOR,
        spaceAfter=6,
    )
    story.append(Paragraph(badge_label, badge_style))

    # --- Document Header Box / Title --------------------------------------
    story.append(Paragraph(_escape(summary.title), styles["DocTitle"]))
    if summary.tagline:
        story.append(Paragraph(_escape(summary.tagline), styles["DocTagline"]))

    meta_parts = []
    if summary.estimated_read_time:
        meta_parts.append(f"⏱ Read Time: {_escape(summary.estimated_read_time)}")
    if source_url:
        meta_parts.append(f"🔗 Source: <a href='{_escape(source_url)}' color='#4338CA'><u>{_escape(source_url)}</u></a>")
    meta_parts.append(f"📅 Generated: {datetime.datetime.now().strftime('%b %d, %Y')}")
    story.append(Paragraph(" &nbsp;|&nbsp; ".join(meta_parts), styles["MetaLine"]))

    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT_COLOR, spaceBefore=0, spaceAfter=14))

    # --- Executive Summary Box --------------------------------------------
    if summary.overview:
        story.append(Paragraph("Executive Summary", styles["SectionHeader"]))
        overview_p = Paragraph(_escape(summary.overview), styles["ExecutiveOverview"])
        overview_table = Table(
            [[overview_p]],
            colWidths=[6.8 * inch],
        )
        overview_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), ACCENT_LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#C7D2FE")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ])
        )
        story.append(overview_table)
        story.append(Spacer(1, 10))

    # --- Key Takeaways Box -----------------------------------------------
    if summary.key_takeaways:
        story.append(Paragraph("Key Takeaways", styles["SectionHeader"]))
        items = [
            ListItem(Paragraph(_escape(point), styles["TakeawayItem"]), leftIndent=12)
            for point in summary.key_takeaways
        ]
        story.append(
            ListFlowable(items, bulletType="bullet", start="circle", leftIndent=8)
        )
        story.append(Spacer(1, 12))

    # --- Table of Contents ------------------------------------------------
    if include_toc:
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=6, spaceAfter=10))
        story.append(Paragraph("Table of Contents", styles["TOCHeading"]))
        toc = TableOfContents()
        toc.levelStyles = [_toc_entry_style(styles)]
        story.append(toc)
        story.append(Spacer(1, 14))

    # --- Sections --------------------------------------------------------
    if summary.sections:
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=6, spaceAfter=10))
        story.append(Paragraph("Detailed Analysis & Key Concepts", styles["SectionHeader"]))
        story.append(Spacer(1, 6))

    for i, section in enumerate(summary.sections):
        sec_elements = []
        heading_text = _escape(section.heading)
        timestamp_str = f" [{_escape(section.timestamp)}]" if section.timestamp else ""
        
        full_heading = f"{i+1}. {heading_text}{timestamp_str}"
        para = Paragraph(f'<a name="section-{i}"/>{full_heading}', styles["SubSectionHeader"])
        para._toc_text = f"{i+1}. {heading_text}"
        para._toc_level = 0
        sec_elements.append(para)

        if section.bullets:
            items = [
                ListItem(Paragraph(_escape(b), styles["BulletText"]), leftIndent=12)
                for b in section.bullets
            ]
            sec_elements.append(
                ListFlowable(items, bulletType="bullet", start="disc", leftIndent=8)
            )

        if section.detail:
            sec_elements.append(Paragraph(_escape(section.detail), styles["DetailText"]))

        if section.key_quote:
            quote_p = Paragraph(f'“{_escape(section.key_quote)}”', styles["QuoteText"])
            quote_table = Table([[quote_p]], colWidths=[6.6 * inch])
            quote_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LINELEFT", (0, 0), (0, -1), 3, ACCENT_COLOR),
                ])
            )
            sec_elements.append(Spacer(1, 4))
            sec_elements.append(quote_table)

        if section.actionable_tips:
            sec_elements.append(Spacer(1, 4))
            tip_items = [
                ListItem(Paragraph(f"<b>Actionable:</b> {_escape(tip)}", styles["TipText"]), leftIndent=12)
                for tip in section.actionable_tips
            ]
            sec_elements.append(
                ListFlowable(tip_items, bulletType="bullet", start="square", leftIndent=8)
            )

        sec_elements.append(Spacer(1, 8))
        story.append(KeepTogether(sec_elements))

    # --- Key Terminology / Glossary --------------------------------------
    if summary.key_terms:
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=10, spaceAfter=10))
        term_elements = [Paragraph("Key Terminology & Concepts", styles["SectionHeader"])]
        table_data = []
        for kt in summary.key_terms:
            t_cell = Paragraph(_escape(kt.term), styles["TermName"])
            d_cell = Paragraph(_escape(kt.definition), styles["TermDef"])
            table_data.append([t_cell, d_cell])

        terms_table = Table(table_data, colWidths=[2.2 * inch, 4.6 * inch])
        terms_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        term_elements.append(terms_table)
        term_elements.append(Spacer(1, 10))
        story.append(KeepTogether(term_elements))

    # --- Deep Dive Q&A Section --------------------------------------------
    if summary.deep_dive_qa:
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=10, spaceAfter=10))
        qa_elements = [Paragraph("Deep Dive Q&A", styles["SectionHeader"])]
        for i, qa in enumerate(summary.deep_dive_qa):
            q_p = Paragraph(f"Q{i+1}: {_escape(qa.question)}", styles["QAQuestion"])
            a_p = Paragraph(f"A: {_escape(qa.answer)}", styles["QAAnswer"])
            qa_elements.extend([q_p, a_p])
        qa_elements.append(Spacer(1, 10))
        story.append(KeepTogether(qa_elements))

    # --- Conclusion Box ---------------------------------------------------
    if summary.conclusion:
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=10, spaceAfter=10))
        conc_elements = [Paragraph("Conclusion & Synthesis", styles["SectionHeader"])]
        conc_p = Paragraph(_escape(summary.conclusion), styles["ExecutiveOverview"])
        conc_table = Table([[conc_p]], colWidths=[6.8 * inch])
        conc_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0FDF4")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#BBF7D0")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ])
        )
        conc_elements.append(conc_table)
        story.append(KeepTogether(conc_elements))

    doc = _TOCDocTemplate(
        str(output_path),
        pagesize=LETTER,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.85 * inch,
        title=summary.title,
    )

    if include_toc:
        doc.multiBuild(story, canvasmaker=NumberedCanvas)
    else:
        doc.build(story, canvasmaker=NumberedCanvas)

    return output_path


class _TOCDocTemplate(BaseDocTemplate):
    def __init__(self, filename, **kwargs):
        super().__init__(filename, **kwargs)
        frame = Frame(
            self.leftMargin,
            self.bottomMargin,
            self.width,
            self.height,
            id="normal",
        )
        self.addPageTemplates([PageTemplate(id="main", frames=frame)])

    def afterFlowable(self, flowable):
        if hasattr(flowable, "_toc_text"):
            self.notify(
                "TOCEntry",
                (flowable._toc_level, flowable._toc_text, self.page),
            )

